Add support for header transferring
adjust/rmq pull request #136
Opened 2023-01-26 15:44 UTC by vearutop

2023-01-27 10:03 UTC, wellle requested changes
This seems like a quite dangerous change as it changes how deliveries are stored in Redis. I think we should explicitly point this out in the PR description, in the Readme and in the release notes of this PR.

It's not a breaking change as it doesn't affect you if you only upgrade but don't start using the headers. But for clients who want to start using the headers I think we need to point out that the rollout needs to be properly planned.

The simplest would probably just be to suggest to update all consumers to run with the new version and be ready to consume deliveries with headers (while still also handling deliveries without headers), before then updating the producers to start producing deliveries with headers.

2023-01-27 10:06 UTC, wellle commented
The approach and the implementation seem very good. 👍

2023-01-27 10:11 UTC, vearutop commented on header.go
> +	lineEnd := strings.Index(payload, "\n")
Header data is serialized to minified JSON, so it should always stay in a single line with line breaks escaped. I'll add a test for such case too. 👍

2023-01-27 10:44 UTC, vearutop commented
@wellle I've added notes on compatibility to README, please check if they are clear enough (if you have better wording, please share).

2023-01-27 10:44 UTC, vearutop commented on header.go
> +	lineEnd := strings.Index(payload, "\n")
Added a test case with line breaks.

2023-01-30 15:39 UTC, wellle approved these changes
Yep, seems good, thank you!

2023-01-30 16:09 UTC, merged